spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  security:
    user:
      password: ${SECURITY_PASSWORD}

server:
  port: 8080